os: linux
dist: xenial
language: ruby

env:
  - COREOS_TRACK=stable
  - COREOS_TRACK=beta
  - COREOS_TRACK=alpha

before_script:
  - pwd
  - echo "curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/current/version.txt -o version.txt"
  - curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/current/version.txt -o version.txt
  - cat version.txt
  - export $(cat version.txt | xargs)
  - git tag --merged master
  - echo "git tag --merged master | grep ${COREOS_VERSION}"
  - if [[ ! -z `git tag --merged master | grep "${COREOS_VERSION}"` ]]; then
      travis_terminate 0;
    fi
  - curl http://download.virtualbox.org/virtualbox/LATEST.TXT -o version.txt
  - cat version.txt
  - export VBOX_VERSION=`cat version.txt`
  - echo "mkdir -p $TRAVIS_BUILD_DIR/deploy"
  - mkdir -p $TRAVIS_BUILD_DIR/deploy

script:
  - echo "docker build
          --build-arg COREOS_VERSION=${COREOS_VERSION}
          --build-arg VBOX_VERSION=${VBOX_VERSION}
          --tag ${DOCKER_USER}/vboxguest:${COREOS_VERSION}
          ."
  - docker build
    --build-arg COREOS_VERSION=${COREOS_VERSION}
    --build-arg VBOX_VERSION=${VBOX_VERSION}
    --tag ${DOCKER_USER}/vboxguest:${COREOS_VERSION}
    .
  - echo "docker create
          --name vboxguest ${DOCKER_USER}/vboxguest:${COREOS_VERSION}
          ."
  - docker create
    --name vboxguest ${DOCKER_USER}/vboxguest:${COREOS_VERSION}
    .
  - echo "docker cp
          vboxguest:/dist/vboxguest.tar.gz
          $TRAVIS_BUILD_DIR/deploy/."
  - docker cp
    vboxguest:/dist/vboxguest.tar.gz
    $TRAVIS_BUILD_DIR/deploy/.

before_deploy:
  - echo "git config --local user.name ${GITHUB_USER}"
  - git config --local user.name "${GITHUB_USER}"
  - echo "git config --local user.email ${GITHUB_EMAIL}"
  - git config --local user.email "${GITHUB_EMAIL}"
  - echo "git tag ${COREOS_VERSION}"
  - git tag "${COREOS_VERSION}"

deploy:
  provider: releases
  token:
    - secure: "fx4J3Su5O6SBgc8UY+F4r73tiW0gNcygmT/I0CPPgN6UXTKss14yefQAeeG+dK4Y08zPB6vSBbUq5dIpbaHK38rTL+sjBeFJPwj12AjvfBKJaE+FUNxxdHfpfealwhF+dlgJI/bpkzeBxebNt1JPZOIt375hH585S4Pl9z5icV2/kDU9bHm/pvvfE2f2EsnpXBcC5Rc0FPrlXxoGrA63ps2Olb9zTFQzwv6BqmCUaL+YUQEolgh3eAy7i1ovaX5xfmn1n7z7Ra4yZLzgbHSWtLg+9cPan2YiW3bCG3fMTUlzzG0kXJkW9IjrebBiIaC1AG8X74oaBnx0oWAGFjg0FaHIqRsqGB9Nk86K+avf+USa2LCiQS66IIkPANdp0WUpwJM93T1mVeeS8V62DN4CmgOaARcVLKIempdrg7D+N8gDx590x1vB5j1Ekco+OXAicGi03P5OjU3GM+coagksuRNquvUNVkO2rrf9a0tKkHCKCxcSm1W/pOrSbePJcEdFrsvQB+zcaUQ201NzQrRFyRkYJz5wrzjStwmq1twZSmuoRvvLsFEHHar+8ibS995gg2skq354K4jJro6rwVnF1I8Z4F5G+ervyUUVsxq2NAL52pAs5ZruRNaUcicHp7Ieaf6iE6UGOT5O9D7uLN7ZJF9Pzb6OawDHMq9GAdVGe0k="
  name: ${COREOS_VERSION}
  tag_name: ${COREOS_VERSION}
  file: deploy/vboxguest.tar.gz
  release_notes: New release for CoreOS:${COREOS_VERSION} with VirtualBox Guest Additions:${VBOX_VERSION}
  cleanup: false

notifications:
  email: false
  slack:
    secure: "eKum3Vbdoj7tgcU5uBeM17GI/yXBu3MHAJeV9MPV3KU0g9yDN8qjrd5/Ukonzu3RHqWDrXBvLuHtTzIBs5y1qIbika7dHWiIPTGIZWSv4EDTUdFWKQCzOhwWXCsO8xsq36Z8wySXFmg/kPs6pEkXaIFv30uUu6SIo/i3MR9j3GFC+Zn8fasL74ju6Ylw+d6kCXsmuSyVzGebl/PyCdOUZ/E2UN11X7zt+RRqF1P3EKC8jznbQMNR3+qGRUeUiS/VQjvlGz8jrfCJZJmJ05bUGBtTztHwip1jaTCjLTTUOyn02YlIzVK06ymW+0NlIWkGI+hFgS0W0ufW32mwG/jaRVL2+RpOmj1OKOlwNLiDURVtZigRWloYS6tv2iyYZ7uxAv+yIG1CzZJBzpm5RBTD+D2BUm+MjG7Uzxd4VdRIqQzrLfGb+gjJlzqfT8OVu2ZNfmYLq6lbSfvtAFmIqRm34y3lN03XebuMapL03APoJc2H2EjOYqz9GDRH0i2X2XphVNTyIS6xwBdZMNOa+niREN7Yb0iPY2ZTkIkkhXy4hGj+eHR1OvtuSgyr45nCTMrosd5n4ppLrRJOsqwqzdNNaRrQ0vLXlzlI5FpxUkwqJSYVH8jB4xdGlrp4x9kDkRvlSSZuuO/7uJHADfQD9iezes/ysw2BLLJ48ztt5VV0Tf0="
